name: WorldGuardAutoFlags
main: com.goyanov.flags.auto.main.WorldGuardAutoFlags
version: 1.1.0
api-version: 1.13
depend:
  - WorldGuard
commands:
  worldguardautoflags:
    description: "§3Reload plugin's configs"
    permission: WorldGuardAutoFlags.admin
    permission-message: "§cYou can't do this!"
    aliases:
      - "wgaf"